name: Sync GitLab to GitHub

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
      - name: Pull and Merge
        run: |
          git clone https://gitlab.postmarketos.org/postmarketOS/pmaports
          cd pmaports
          mkdir -pv .github
          mkdir -pv .github/workflows
          wget https://github.com/dpkg123/pmaports/raw/master/.github/workflows/main.yml -O .github/workflows/main.yml 
          git remote set-url origin https://github.com/dpkg123/pmaports
          git add .
          git status
          git commit -m "Merge branch master from https://gitlab.postmarketos.org/postmarketOS/pmaports into master" --author "Jalt Brown <root@laptop>"
        
      - name: GitHub Push
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          directory: pmaports
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
